### ISSUE TITLE
Save Button doesn't appear when editing a Marker that was already edited once

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#210] opened 2016-07-18 19:28 UTC
## Steps to replicate
* Drop a Places Maker, try "Werewolf American Pub" in San Diego
* Click on the Pencil to edit the marker
* Change the icon, the colors, etc. then save those changes
* Save the marker
* Edit the marker again without saving the map, and click the Pencil again

**Result:** The save button for the custom icon and colors is not in the modal anymore and you can't save new changes.

Note that this is on the current live FREE version, I haven't tested this with the new refactor yet.

**Comment by DevinWalker** [comment] 2016-08-01 23:54
This is a duplicate of https://github.com/WordImpress/Google-Maps-Builder/issues/210 which is slated for 2.2

**Closed by DevinWalker** 2016-08-01 23:54 UTC
Labels: bug
