### ISSUE TITLE
TypeError: $(...).qtip is not a function

### ISSUE THREAD

**Issue by DarwinOnLine** [WordImpress/Google-Maps-Builder#259] opened 2017-12-27 08:36 UTC
Hello,

When I try to create or update an existing map, I have this error :
`TypeError: $(...).qtip is not a function`

Trace 
<pre>gmb.initialize_tooltips     /wp-content/plugins/google-maps-builder/vendor/wordimpress/maps-builder-core/assets/js/admin/admin-google-map.min.js:1:28364
gmb.init                    /wp-content/plugins/google-maps-builder/vendor/wordimpress/maps-builder-core/assets/js/admin/admin-google-map.min.js:1:92
&lt;anonyme&gt;                   /wp-content/plugins/google-maps-builder/vendor/wordimpress/maps-builder-core/assets/js/admin/admin-google-map.min.js:1:29129
dispatch                    /wp-admin/load-scripts.php:3:12392
add/r.handle                /wp-admin/load-scripts.php:3:9156</pre>

Occurred on Wordpress 4.9.1 and plugin 2.1.2

**Comment by mathetos** [comment] 2017-12-28 22:18
Hi @DarwinOnLine this is most often caused by one of the following:

1) Your site enqueue's a custom version of jQuery instead of WordPress's default version. 
2) You have JS minification or concatenation via a caching plugin and it's causing our script to be loaded before jQuery.

Can you eliminate those two items from being the cause of this?

**Comment by DarwinOnLine** [comment] 2017-12-31 15:05
Hello Matt,

Thank you for your response, I have some additional information about this issue. In the admin page, the HTML rendering seems to be brutally stopped after that :
```html
<label for="gmb_theme_json">Custom Map Theme JSON</label>
</div>
	<div class="cmb-td">
```
So, actually the dedicated jQuery is not present since it is not declared...

No custom jQuery and no JS minification, problem occur in admin section (`/wp-admin/post.php?post=1234&action=edit`) and no custom behavior has been added.

**Comment by DarwinOnLine** [comment] 2017-12-31 15:56
OK, problem solved. My web host have upgraded PHP version from 7.1 to 7.2. I went back to 7.1 and everything works fine.

**Comment by DevinWalker** [comment] 2018-07-31 19:14
Closing in favor of #217

**Closed by DevinWalker** 2018-07-31 19:14 UTC

**Comment by imansugirman** [comment] 2018-09-19 07:42
Error DIsable Open Map Builder 
![jepretan layar 2018-09-19 pada 14 42 03](https://user-images.githubusercontent.com/38036171/45738317-448c0a00-bc1a-11e8-8860-956b59bd9063.png)

**Comment by pimmesz** [comment] 2018-11-21 13:00
> Error DIsable Open Map Builder
> ![jepretan layar 2018-09-19 pada 14 42 03](https://user-images.githubusercontent.com/38036171/45738317-448c0a00-bc1a-11e8-8860-956b59bd9063.png)

Same issue here!
